### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by githubteacher** [githubschool/sticky-tape#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by erictwalker18** [comment]
anything

**Comment by dmistrymmm** [comment]
## Yay!

**Comment by karlbz** [comment]
Add me please.

**Comment by Brian-Stankiewicz** [comment]
Woohoo

**Comment by kingebri** [comment]
how now brown cow

**Comment by rwshannon** [comment]
Please add me as a collaborator.

**Comment by npshrader** [comment]
#npshrader

**Comment by bdmurray** [comment]
Me too!

**Comment by githubteacher** [comment]
Ⓜ️ Ⓜ️ Ⓜ️

**Comment by jgandrud** [comment]
# I love emojis :+1: :100:

**Comment by jfschumacher** [comment]
anything

**Comment by githubteacher** [comment]
Comment

**Comment by erictwalker18** [comment]
@githubteacher have more emails
